export * from "./appointment";
export * from "./calendar";
export * from "./degree";
export * from "./grade";
export * from "./module";
export * from "./semester";
export * from "./settings";
export * from "./token";
export * from "./user";
