services:
  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/1_create_database.sql
      - ./db/create_tables.sql:/docker-entrypoint-initdb.d/2_create_tables.sql


  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=john.doe@example.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"

    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local

# Container Stoppen: docker-compose -f docker-compose.dev.yml down
# Container Starten: docker-compose -f docker-compose.dev.yml up