import { Module } from "@/types";

const mockModules: Module[] = [
  {
    id: "module-1",
    userId: "user-1",
    degreeId: "degree-1",
    semesterId: "semester-11",
    name: "Web Development",
    description: "Module",
    ects: 4,
    complexity: 9,
    understanding: 8,
    time: 7,
  },
  {
    id: "module-2",
    userId: "user-1",
    degreeId: "degree-1",
    semesterId: "semester-11",
    name: "Software Development",
    description: "Module",
    ects: 4,
    complexity: 8,
    understanding: 7,
    time: 6,
  },
  {
    id: "module-3",
    userId: "user-1",
    degreeId: "degree-1",
    semesterId: "semester-12",
    name: "Database Systems",
    description: "Module",
    ects: 4,
    complexity: 9,
    understanding: 9,
    time: 8,
  },
  {
    id: "module-4",
    userId: "user-1",
    degreeId: "degree-1",
    semesterId: "semester-12",
    name: "Computer Networks",
    description: "Module",
    ects: 4,
    complexity: 7,
    understanding: 6,
    time: 7,
  },
  {
    id: "module-5",
    userId: "user-1",
    degreeId: "degree-1",
    semesterId: "semester-21",
    name: "Algorithms and Data Structures",
    description: "Module",
    ects: 4,
    complexity: 10,
    understanding: 8,
    time: 8,
  },
  {
    id: "module-6",
    userId: "user-1",
    degreeId: "degree-1",
    semesterId: "semester-23",
    name: "Operating Systems",
    description: "Module",
    ects: 4,
    complexity: 9,
    understanding: 7,
    time: 7,
  },
  {
    id: "module-7",
    userId: "user-1",
    degreeId: "degree-1",
    semesterId: "semester-23",
    name: "Artificial Intelligence",
    description: "Module",
    ects: 4,
    complexity: 10,
    understanding: 9,
    time: 8,
  },
  {
    id: "module-8",
    userId: "user-1",
    degreeId: "degree-1",
    semesterId: "semester-24",
    name: "Machine Learning",
    description: "Module",
    ects: 4,
    complexity: 10,
    understanding: 8,
    time: 9,
  },
];

export { mockModules };
