package ch.zhaw.studyflow.domain.studyplan;

import java.util.List;

/**
 * Interface for the study plan algorithm.
 * This interface provides methods to run the algorithm, get study days, create study days, and allocate modules.
 */
public interface StudyplanAlgorithm {

    /**
     * Runs the study plan algorithm.
     *
     * @return a list of module allocations generated by the algorithm
     */
    List<ModuleAllocation> runAlgorithm();

    /**
     * Returns the list of study days generated by the algorithm.
     *
     * @return the list of study days
     */
    List<StudyDay> getStudyDays();

    /**
     * Returns the total available minutes for the study plan.
     *
     * @return the total available minutes
     */
    int getTotalAvailableMinutes();

    /**
     * Creates the study days based on the algorithm's logic.
     */
    void createStudyDays();

    /**
     * Allocates modules to the study days based on the algorithm's logic.
     */
    void allocateModules();
}